Update deploy-app.yml

diff --git a/.github/workflows/deploy-app.yml b/.github/workflows/deploy-app.yml
--- a/.github/workflows/deploy-app.yml
+++ b/.github/workflows/deploy-app.yml
@@ -58,7 +58,7 @@ jobs:
       - name: Test VPN Connectivity
         run: |
           set -e
-          sudo ping -c "${{ secrets.WG_SUB_NETWORK }} || (echo "VPN Ping failed!" && exit 1)
+          sudo ping -c "${{ secrets.WG_SUB_NETWORK }}" || (echo "VPN Ping failed!" && exit 1)
 
       - name: Test SSH Connection
         run: |
