Update Pipeline for use docker compose script.

diff --git a/.github/workflows/deploy-app.yml b/.github/workflows/deploy-app.yml
--- a/.github/workflows/deploy-app.yml
+++ b/.github/workflows/deploy-app.yml
@@ -24,6 +24,16 @@ jobs:
       - name: Build Angular Application
         run: npm run build
 
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3.10.0
+
+      - name: Build Docker image
+        uses: docker/build-push-action@v6.15.0
+        with:
+          context: .
+          tags: list_client_app:latest
+          load: true
+
       - name: Install WireGuard et SSHPass
         run: |
           set -e
@@ -40,7 +50,7 @@ jobs:
       - name: Test VPN Connectivity
         run: |
           set -e
-          sudo ping -c 3 10.8.0.4 || (echo "VPN Ping failed!" && exit 1)
+          sudo ping -c "${{ secrets.WG_SUB_NETWORK }} || (echo "VPN Ping failed!" && exit 1)
 
       - name: Test SSH Connection
         run: |
@@ -55,9 +65,11 @@ jobs:
           username: ${{ secrets.SSH_USER }}
           password: ${{ secrets.SSH_PASSWORD }}
           port: "22"
-          source: "dist/list_client/browser/."
-          target: "list_app/client/"
-          overwrite: true
+          script: |
+            cd list_app/client/
+            sudo docker compose down
+            sudo docker load -i list_client_app.tar || true
+            TAG=$(git rev-parse --short HEAD) sudo docker compose up -d
 
       - name: Cleanup VPN
         if: always()
