Update Pipeline.

diff --git a/.github/workflows/deploy-app.yml b/.github/workflows/deploy-app.yml
--- a/.github/workflows/deploy-app.yml
+++ b/.github/workflows/deploy-app.yml
@@ -24,13 +24,30 @@ jobs:
       - name: Build Angular Application
         run: npm run build
 
-      - name: Configure WireGuard
+      - name: Install WireGuard
         run: |
+          set -e
           sudo apt update
           sudo apt install -y wireguard-tools
+
+      - name: Configure WireGuard
+        run: |
           echo "${{ secrets.WG_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null
-          sudo wg-quick up wg0
-          sudo ping -c 3 10.8.0.1 || exit 1
+          sudo wg-quick up wg0 || (echo "WireGuard failed to start!" && exit 1)
+          sleep 3
+          sudo wg
+
+      - name: Test VPN Connectivity
+        run: |
+          set -e
+          ip a | grep wg0 || (echo "WireGuard interface not found!" && exit 1)
+          ip route || (echo "No routing information!" && exit 1)
+          sudo ping -c 3 10.8.0.1 || (echo "VPN Ping failed!" && exit 1)
+
+      - name: Test SSH Connection
+        run: |
+          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'" || (echo "SSH connection failed!" && exit 1)
+
 
       - name: Deploy to Server from SCP.
         uses: appleboy/scp-action@v0.1.7
